class Pais():

    codigo = {
         'AD' :	'Andorra'
        ,'AE' :	'Emiratos Árabes Unidos'
        ,'AF' :	'Afganistán'
        ,'AG' :	'Antigua y Barbuda'
        ,'AI' :	'Anguila'
        ,'AL' :	'Albania'
        ,'AM' :	'Armenia'
        ,'AN' :	'Antillas Neerlandesas'
        ,'AO' :	'Angola'
        ,'AQ' :	'Antártida'
        ,'AR' :	'Argentina'
        ,'AS' :	'Samoa Americana'
        ,'AT' :	'Austria'
        ,'AU' :	'Australia'
        ,'AW' :	'Aruba'
        ,'AX' :	'Islas Áland'
        ,'AZ' :	'Azerbaiyán'
        ,'BA' :	'Bosnia y Herzegovina'
        ,'BB' :	'Barbados'
        ,'BD' :	'Bangladesh'
        ,'BE' :	'Bélgica'
        ,'BF' :	'Burkina Faso'
        ,'BG' :	'Bulgaria'
        ,'BH' :	'Bahréin'
        ,'BI' :	'Burundi'
        ,'BJ' :	'Benin'
        ,'BL' :	'San Bartolomé'
        ,'BM' :	'Bermudas'
        ,'BN' :	'Brunéi'
        ,'BO' :	'Bolivia'
        ,'BR' :	'Brasil'
        ,'BS' :	'Bahamas'
        ,'BT' :	'Bhután'
        ,'BV' :	'Isla Bouvet'
        ,'BW' :	'Botsuana'
        ,'BY' :	'Belarús'
        ,'BZ' :	'Belice'
        ,'CA' :	'Canadá'
        ,'CC' :	'Islas Cocos'
        ,'CF' :	'República Centro-Africana'
        ,'CG' :	'Congo'
        ,'CH' :	'Suiza'
        ,'CI' :	'Costa de Marfil'
        ,'CK' :	'Islas Cook'
        ,'CL' :	'Chile'
        ,'CM' :	'Camerún'
        ,'CN' :	'China'
        ,'CO' :	'Colombia'
        ,'CR' :	'Costa Rica'
        ,'CU' :	'Cuba'
        ,'CV' :	'Cabo Verde'
        ,'CX' :	'Islas Christmas'
        ,'CY' :	'Chipre'
        ,'CZ' :	'República Checa'
        ,'DE' :	'Alemania'
        ,'DJ' :	'Yibuti'
        ,'DK' :	'Dinamarca'
        ,'DM' :	'Domínica'
    }